standards:
  enabled:
  - microsoft
  - ecocode
  - suscom
  - gsf
  - nvidia
  rules:
    disable:
    - no_infinite_loops
    - gpu_utilization
    - inefficient_loop
    - no_n2_algorithms
    - proper_resource_cleanup
    - unnecessary_computation
    - algorithm_efficiency
    enable: []
