standards:
  enabled:
  - microsoft
  - nvidia
  - ecocode
  - gsf
  - suscom
  rules:
    disable:
    - no_n2_algorithms
    - proper_resource_cleanup
    - gpu_utilization
    - no_infinite_loops
    - algorithm_efficiency
    - inefficient_loop
    - unnecessary_computation
    enable: []
