standards:
  enabled:
  - suscom
  - microsoft
  - ecocode
  - nvidia
  - gsf
  rules:
    disable:
    - no_n2_algorithms
    - inefficient_loop
    - unnecessary_computation
    - proper_resource_cleanup
    - no_infinite_loops
    - algorithm_efficiency
    - gpu_utilization
    enable: []
