standards:
  enabled:
  - suscom
  - gsf
  - ecocode
  - microsoft
  - nvidia
  rules:
    disable:
    - unnecessary_computation
    - gpu_utilization
    - algorithm_efficiency
    - no_n2_algorithms
    - proper_resource_cleanup
    - inefficient_loop
    - no_infinite_loops
    enable: []
